# Plugin information
name: "Db Validators"
description: "Plugin de validaciones para campos de modelos."
version: "2.0"
framework_version: "2.0"
dependencies: "db_base"
notes: ""
# Author information
author: "Paul Marclay"
email: "paul.eduardo.marclay@gmail.com"
site: ""
# Legal information
company: "Dolem Labs"
copyright: "(c) 2012 - Paul Marclay"
license: "GNU GENERAL PUBLIC LICENSE"